# Generated by Django 5.2 on 2025-04-27 21:26

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploader_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy_score', models.IntegerField(default=100)),
                ('tag', models.CharField(choices=[('MBTI', 'MBTI'), ('Enneagram', 'Enneagram'), ('Socionics', 'Socionics'), ('Tempraments', 'Tempraments'), ('Psychosophy', 'Psychosophy'), ('Big Five', 'Big Five'), ('DISC', 'DISC'), ('Zodiac', 'Zodiac'), ('Astrology', 'Astrology'), ('Numerology', 'Numerology'), ('Tarot', 'Tarot'), ('Human Design', 'Human Design'), ('Other', 'Other')], default='Other', max_length=20)),
                ('file', models.FileField(upload_to=vault.models.upload_to_tag_folder)),
            ],
        ),
    ]
