# Generated by Django 5.2 on 2025-04-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('category', 'Category'), ('language', 'Language')], default='category', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='tag',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='tags',
            field=models.ManyToManyField(related_name='pdf_documents', to='vault.tag'),
        ),
    ]
